version: '3.8'

services:
  flask_app:
    image: gregogs/testings:flask-V1
    container_name: flask_container
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O /dev/null http://flask_app:5000/healthz" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network
  website:
    image: busybox:latest
    command: ["sleep", "infinity"]
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://flask_app:5000/healthz"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network
  selenium:
    image: selenium/standalone-chromium:latest
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app_network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://flask_app:5000/healthz && curl -f http://localhost:4444" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
  unit_test:
    depends_on:
      website:
        condition: service_healthy
      selenium:
        condition: service_healthy
    build:
      context: .
    image: gregogs/testings:ruby-V1
    command:
      - --pattern
      - /tests/utest/*_spec.rb
    networks:
      - app_network
networks:
  app_network:
    driver: bridge