apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: flask-application
  template:
    metadata:
      labels:
        app: flask-application
    spec:
      containers:
      - name: flask-app
        image: gregogs/testings:flask-V1
        ports:
        - containerPort: 5000 # Replace with your Flask app's port
---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
spec:
  type: ClusterIP # Exposes the service on a cluster-internal IP.
  selector:
    app: flask-application # Must match the deployment's label.
  ports:
    - protocol: TCP
      port: 8080  # The port exposed by the service.
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
spec:
  rules:
    - host: k8s.testing.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-svc
                port:
                  number: 8080
          - path: /flask
            pathType: Prefix
            backend:
              service:
                name: flask-svc
                port:
                  number: 8080
          - path: /docker
            pathType: Prefix
            backend:
              service:
                name: flask-svc
                port:
                  number: 8080
