version: '3.8'

services:
  flask_app:
    image: gregogs/testings:flask-V1.1
    container_name: flask_container
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O /dev/null http://flask_app:5000/healthz" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_network
networks:
  app_network:
    driver: bridge